{% set version = "0.1.0a6" %}

package:
  name: dask-geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/dask-geopandas/releases/download/v{{ version }}/dask-geopandas-{{ version }}.tar.gz
  sha256: 1cce04bb9d00653a7f2abd2ad7b31cb61e0dbce436ee46fcb201fc11dcaa9307

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - geopandas-base >=0.10
    - dask-core >=2021.06.0
    - pygeos
    - packaging

test:
  imports:
    - dask_geopandas

about:
  home: https://github.com/geopandas/dask-geopandas
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Parallel GeoPandas with Dask 

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
