{% set version = "0.1.0a4" %}

package:
  name: dask-geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/dask-geopandas/releases/download/v{{ version }}/dask-geopandas-{{ version }}.tar.gz
  sha256: 4ddce8fe5f5f4eb104485a412200af17490b0ef067a5409853099b1830820fb4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopandas >=0.9
    - dask >=2.2.0
    - distributed >=2.2.0

test:
  imports:
    - dask_geopandas

about:
  home: https://github.com/geopandas/dask-geopandas
  license: BSD-3-Clause
  license_file: LICENSE
  summary: GeoPandas objects backed with Dask

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
