{% set name = "dask-geopandas" %}
{% set version = "0.4.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 95d1a08fcb0dc47454628b89dee2e89dd63df6c31183746a58b4908a2dc21e96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - geopandas-base >=0.12
    - shapely >=2.0
    - dask-core >=2022.06.0
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - dask_geopandas

about:
  home: https://github.com/geopandas/dask-geopandas
  summary: Parallel GeoPandas with Dask
  dev_url: https://github.com/geopandas/dask-geopandas/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
