{% set name = "dask-geopandas" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-geopandas-{{ version }}.tar.gz
  sha256: 032012d1dfd4d47b0009c3f89995fe5ee434edbaac78cac398637ceade9b26c3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - geopandas-base >=0.10
    - dask-core >=2021.06.0
    - distributed >=2021.06.0
    - packaging
  run_constrained:
    - shapely >=2.0

test:
  imports:
    - dask_geopandas
  commands:
    - pip check
  requires:
    - pip
    - fiona

about:
  home: https://github.com/geopandas/dask-geopandas
  summary: Parallel GeoPandas with Dask
  dev_url: https://github.com/geopandas/dask-geopandas/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
