{% set name = "dask-geopandas" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d63cd39cbc25d724cf804e10fa935eea90eb7d7a006517f5f23ab0b5c340beb4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - geopandas-base >=0.12
    - shapely >=2.0
    - dask-core >=2022.06.0
    - packaging

test:
  imports:
    - dask_geopandas

about:
  home: https://github.com/geopandas/dask-geopandas
  summary: Parallel GeoPandas with Dask
  dev_url: https://github.com/geopandas/dask-geopandas/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
