{% set name = "dask-geopandas" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b12b89d3845cd32feb4d3040881a1e1a8537dad48c77457194f0653089458837

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - geopandas-base >=0.10
    - dask-core >=2021.06.0
    - packaging

test:
  imports:
    - dask_geopandas

about:
  home: https://github.com/geopandas/dask-geopandas
  summary: Parallel GeoPandas with Dask
  dev_url: https://github.com/geopandas/dask-geopandas/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinfleis
    - jorisvandenbossche
    - jsignell
